name:                YOURPKG
# synopsis:            A quick description of your package.
version:             0.1.0.0
license:             BSD-3-Clause
author:              Seth Etter
maintainer:          mail@sethetter.com
# github:              sethetter/YOURPKG

ghc-options: -Wall

dependencies:
  - base ^>=4.12.0.0
  - text

source-dirs:
  - src

executables:
  my-executable:
    main: src/Main.hs

tests:
  spec:
    main: test/Main.hs
    source-dirs:
      - test
    dependencies:
      - hspec
